FROM mcr.microsoft.com/devcontainers/python:3.11-bullseye

WORKDIR /workspace

ARG ARCH=amd64
RUN sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add - && \
    sudo apt-add-repository "deb [arch=${ARCH}] https://apt.releases.hashicorp.com $(lsb_release -cs) main" && \
    sudo apt-get update && sudo apt-get install terraform

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf awscliv2.zip ./aws

# Download and install the AWS SAM CLI
RUN curl -Lo sam-installation.sh https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip \
    && unzip sam-installation.sh -d sam-installation \
    && ./sam-installation/install \
    && rm -rf sam-installation.sh sam-installation

RUN pip install notebook

# Install Node.js
# RUN apt-get update && apt-get install -y nodejs npm

 