FROM mcr.microsoft.com/devcontainers/python:3.11-bullseye

WORKDIR /workspace

ARG ARCH=amd64
RUN sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add - && \
    sudo apt-add-repository "deb [arch=${ARCH}] https://apt.releases.hashicorp.com $(lsb_release -cs) main" && \
    sudo apt-get update && sudo apt-get install terraform

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf awscliv2.zip ./aws

# Download and install the AWS SAM CLI
RUN curl -Lo sam-installation.sh https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip \
    && unzip sam-installation.sh -d sam-installation \
    && ./sam-installation/install \
    && rm -rf sam-installation.sh sam-installation

RUN pip install notebook

# Install Node.js
ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 20.10.0

RUN mkdir -p $NVM_DIR
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash \
    && . $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default
ENV NODE_PATH $NVM_DIR/versions/node/v$NODE_VERSION/lib/node_modules
ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

RUN npm install -g react react-dom 
RUN npm install -g webpack webpack-dev-server webpack-cli
RUN npm install -g babel-core babel-loader babel-preset-env babel-preset-react babel-webpack-plugin
RUN npm install -g serve
 