FROM python:3.11-slim

WORKDIR /usr/src/app

RUN pip install jupyter
RUN pip install nbconvert
RUN pip install pandas
RUN pip install boto3
RUN pip install requests

COPY ./app /usr/src/app
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "app.py"]
